recipe: default.v1
language: zh

pipeline:
- name: WhitespaceTokenizer
- name: JiebaTokenizer
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: rasa/LaBSE
- name: RegexFeaturizer
- name: DIETClassifier
  epochs: 100
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.5

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy