recipe: default.v1
language: ch

pipeline:
- name: HFTransformersNLP
  model_name: bert
  model_weights: bert-base-multilingual-cased
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: RegexFeaturizer
- name: DIETClassifier
  epochs: 200
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.5

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy