recipe: default.v1
language: ch

pipeline:
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.5

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy